### PR TITLE
feat: allow getting installed binary path

### PR DESCRIPTION
**Pull request by achingbrain**
Lets you install this module locally or globally, it's up to you!

If you install it locally though, you probably want to know where the binary is installed:

```javascript
const ipfs = require('go-ipfs')

console.info('ipfs is installed at', ipfs.path())
```

Essentially adds the downloading bit of `ipfs/npm-go-ipfs-dep` to this module, so you can either:

```console
$ npm install --save go-ipfs
// cool, it's in my project as a dep now
```

or

```console
$ npm install -g go-ipfs
// it's installed globally for my node install!
```

I've also removed the old jenkins config as we don't use it any more and added similar github actions for publishing to `ipfs/npm-go-ipfs-dep`.  That module should be retired and this one moved to the main ipfs org.

Closes https://github.com/ipfs/npm-go-ipfs-dep/issues/42

### CODE REVIEW

**Comment by Stebalien** [comment]
I like the idea but I'm way out of my depth here.

**Comment by achingbrain** [comment]
@Stebalien can this be merged & released?

**Comment by Stebalien** [comment]
Ah, sorry, I assumed you had write access. cc @daviddias.

**Comment by Stebalien** [comment]
@achingbrain I can't cut a new release without a new go-ipfs release, apparently.

**Pull request merged**
